[platformio]
default_envs = display, sensornode
src_dir = .

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_USB_CDC_ON_BOOT=0

[env:display]
upload_port = COM14
monitor_port = COM14
build_src_filter =
    +<Display/src/>
    +<Shared/src/>
    -<SensorNode/src/>
build_flags =
    ${env.build_flags}
    -IDisplay/include
    -IShared/include
board_build.filesystem = littlefs
lib_deps =
    moononournation/GFX Library for Arduino @ ^1.5.6
    paulstoffregen/XPT2046_Touchscreen
    WiFi
    NetworkClientSecure
    HTTPClient
    Update

[env:sensornode]
upload_port = COM9
monitor_port = COM9
build_src_filter =
    +<SensorNode/src/>
    +<Shared/src/>
    -<Display/src/>
build_flags =
    ${env.build_flags}
    -ISensorNode/include
    -IShared/include
